[project]
name = "mallorn"
version = "0.1.0"
description = ""
authors = [
    { name = "Nguyễn Tư Đức", email = "23021534@gmail.com" },
    { name = "Phạm Trung Hiếu", email = "23021554@vnu.edu.vn "}
]
license = "BSD-3-Clause"
readme = "README.md"
requires-python = ">=3.14"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
xgboost = "^3.1.2"
lightgbm = "^4.6.0"
# catboost = "^1.2.8"
numpy = "^2.3.5"
pandas = "^2.3.3"
scikit-learn = "^1.7.2"
extinction = "^0.4.8"
optuna = "^4.6.0"
light-curve = "^0.10.5"
pyarrow = "^22.0.0"

[tool.poetry.dependencies.kaggle]
git = "https://github.com/NTDuck/kaggle-api.git"
rev = "fe304755f030d45676fd22eb686d37065abadada"

[tool.poetry.group.dev.dependencies]
python-dotenv = ">=1.2.1,<2.0.0"
ipykernel = "^7.1.0"

[tool.poetry.scripts]
kaggle-download = "scripts.kaggle:download"
autogluon = "mallorn.autogluon:main"
